name: Reflex
main: com.shawckz.reflex.Reflex
version: ${project.version}
authors: [Shawckz]
website: https://shawckz.com/product/Reflex
depend: [ProtocolLib]
description: Reflex Anti-Cheat by Shawckz | https://shawckz.com