name: Reflex
main: com.shawckz.reflex.Reflex
version: 1.0.0
authors: [Shawckz]
website: http://shawckz.com/project/reflex
depend: [ProtocolLib, ShawXAuth]
description: Reflex Anti-Cheat by Shawckz | http://shawckz.com